import { FormLabel, Input, Button } from '@material-ui/core';
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import styles from '../styles/Home.module.css'

export default function Home() {
  let [result, setResult] = useState('');

  const submitHandler = ($event) => {
    $event.preventDefault();

    const form = new FormData();
    form.append('firstName', document.getElementById("f").value)
    form.append('lastName', document.getElementById("l").value)

    fetch("http://localhost:8000/user", {
      method: "POST",
      body: form,
    }).then(result => result.text())
    .then(res => setResult(res))
    .catch(err => console.log(err))

  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        
        <div className={styles.grid}>
          <form encType="multipart/form-data" onSubmit={submitHandler} method="POST">
            <FormLabel htmlFor="f">First Name: </FormLabel>
            <Input type="text" id="f" name="firstname"/>
            &emsp;
            <FormLabel htmlFor="l">Last Name: </FormLabel>
            <Input type="text" id="l" name="lastname"/>
            &emsp;
            <Button type="submit" variant="contained" color="primary">submit</Button>
          </form>
        </div>
        <br />
        <div>{result}</div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
